package com.virtenio.preon32.examples.basic.timer;

import com.virtenio.driver.timer.NativeTimer;
import com.virtenio.driver.timer.Timer;
import com.virtenio.driver.timer.TimerException;
import com.virtenio.vm.Time;
import com.virtenio.vm.event.AsyncEvent;
import com.virtenio.vm.event.AsyncEventHandler;
import com.virtenio.vm.event.AsyncEvents;

/**
 * Example to compare the time generated by a local RTC with the time generated
 * by a local timer. The RTC time is used as a reference time. The time of the
 * timer is based on the CPU clock which has a little inaccuracy.
 */
public class TimeComparatorExample {
	/**
	 * The test method which runs the test.
	 */
	public static void main(String[] args) throws TimerException {
		final int delta = 1000; // the output interval
		final int eventId = 0;

		// add handler to event system because timer generates events.
		AsyncEvents events = AsyncEvents.getAsyncEvents();
		AsyncEvent event = events.getEvent(eventId);
		event.addHandler(new AsyncEventHandler() {
			int counter;
			long start;

			@Override
			public void handleAsyncEvent(int eventId) {
				if (start == 0) {
					start = Time.millis();
				}
				long v = Time.millis() - start;
				System.out.println("RTC: " + v + ", Timer:" + counter);
				counter += delta;
			}
		});
		events.start();

		// open the timer to generate events
		NativeTimer timer = NativeTimer.getInstance(0);
		timer.open(Timer.MODE_CONTINUOUS, eventId, delta);
		timer.enable();
	}
}
